### ISSUE TITLE
makepkg fails for libnvidia-container v1.9.0

### ISSUE THREAD

**Issue by dtenbrinck** [julie-is-late/aur-libnvidia-container#12]
Dear maintainers,

when running `makepkg -s` on a fully updated Arch Linux system for this AUR package the build process aborts with the following error messages:

```
[...]

/usr/bin/ld: warning: /tmp/libnvidia-container/src/libnvidia-container-1.9.0/src/libnvidia-container.lds contains output sections; did you forget -T?
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../lib/libelf.a(elf_error.o): relocation R_X86_64_TPOFF32 against `global_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:231: libnvidia-container.so.1.9.0] Error 1
```

So far I have no idea what leads to this problem. Are there any suggestions?

Thanks in advance!

**Comment by julie-is-late** [comment]
Hi, please ask comments like this on the [aur webpage](https://aur.archlinux.org/packages/libnvidia-container) instead of here. this repo basically just exists for me and kiendang to talk to each other and coordinate. 

Also please don't email my personal email, it's not even the one linked in the PKGBUILD. 

for what it's worth, `makepkg -s` works on all my machines.

**Comment by dtenbrinck** [comment]
Sorry! I created an issue because @kiendang suggested me to do so. If you don't want interactions from the community here, you could state this on the front page of this repository or make the repo private.

Thanks for checking! I fixed my problem by forcing a reinstall of all dependencies of this AUR package. At least one dependency must have been broken, because now it works fine.
