### ISSUE TITLE
1.0.0_0.1.beta.1-1 is > 1.0.0-1

### ISSUE THREAD

**Issue by julie-is-late** [julie-is-late/aur-libnvidia-container#4]
at least according to pacman it is. so if we push `1.0.0-1` the epoch number will need bumped.

**Comment by kiendang** [comment]
you mean pkgver 1.0.0 and pkgrel 2?

**Comment by julie-is-late** [comment]
`1.0.0_0.1.beta.1-1` is the current version on the aur. so pushing `v1.0.0` as is would not result in people getting the update because their local version is newer

**Comment by kiendang** [comment]
Or wait for the guy to reply and do `1.0.1`, but looks like not only [libnvidia-container](https://github.com/NVIDIA/libnvidia-container.git) but also [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime.git) didn't have their latest stable version released on github.

Personally I think git commit as source is fine tho. It's almost impossible to change a commit referred to by hash. For `nvidia-container-runtime` I have to do it anyway because it's a patch of [opencontainers/runc](https://github.com/opencontainers/runc.git) and checks out a specific commit from there.

It's also written [here](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git)
> Version control systems can be used for retrieval of source code for both usual statically versioned packages and latest (trunk) version of a development branch.

**Comment by julie-is-late** [comment]
Nice find on the docs, guess it's fine then. that said, the package did get a new release to match the version, so probably wont change it for now.

**Comment by kiendang** [comment]
> the package did get a new release to match the version

this is cool
